Removed the use of gardenctl

diff --git a/.ci/local_integration_test b/.ci/local_integration_test
--- a/.ci/local_integration_test
+++ b/.ci/local_integration_test
@@ -83,55 +83,34 @@ then
       exit 1
 fi
 
+printf "\e[34mEnter the project name\e[0m\n"
+read PROJECT
+if [ -z "$PROJECT" ]
+then
+    printf "\e[31mproject cannot be empty\e[0m\n"
+    exit 1
+fi
+printf "\e[34mEnter the control cluster name\e[0m\n"
+read CONTROL_CLUSTER
+if [ -z "$CONTROL_CLUSTER" ]
+then
+    printf "\e[31mseed name cannot be empty\e[0m\n"
+    exit 1
+fi
+printf "\e[34mEnter the target cluster name\e[0m\n"
+read TARGET_CLUSTER
+if [ -z "$TARGET_CLUSTER" ]
+then
+    printf "\e[31mtarget cluster cannot be empty\e[0m\n"
+    exit 1
+fi
+
+cd $MCM_REPO_PATH
 if [ "$IS_CONTROL_CLUSTER_SEED" = true ]
 then
-    cd $MCM_REPO_PATH
-    printf "\e[34mEnter the project name\e[0m\n"
-    read PROJECT
-    if [ -z "$PROJECT" ]
-    then
-        printf "\e[31mproject cannot be empty\e[0m\n"
-        exit 1
-    fi
-    printf "\e[34mEnter the seed name\e[0m\n"
-    read CONTROL_CLUSTER
-    if [ -z "$CONTROL_CLUSTER" ]
-    then
-        printf "\e[31mseed name cannot be empty\e[0m\n"
-        exit 1
-    fi
-    printf "\e[34mEnter the target cluster name\e[0m\n"
-    read TARGET_CLUSTER
-    if [ -z "$TARGET_CLUSTER" ]
-    then
-        printf "\e[31mtarget cluster cannot be empty\e[0m\n"
-        exit 1
-    fi
     ./hack/gardener_local_setup.sh --seed "$CONTROL_CLUSTER" --shoot "$TARGET_CLUSTER" --project "$PROJECT" --provider aws
     cd -
 else
-    cd $MCM_REPO_PATH
-    printf "\e[34mEnter the project name\e[0m\n"
-    read PROJECT
-    if [ -z "$PROJECT" ]
-    then
-        printf "\e[31mproject cannot be empty\e[0m\n"
-        exit 1
-    fi
-    printf "\e[34mEnter the control cluster name\e[0m\n"
-    read CONTROL_CLUSTER
-    if [ -z "$CONTROL_CLUSTER" ]
-    then
-        printf "\e[31mcontrol cluster cannot be empty\e[0m\n"
-        exit 1
-    fi
-    printf "\e[34mEnter the target cluster name\e[0m\n"
-    read TARGET_CLUSTER
-    if [ -z "$TARGET_CLUSTER" ]
-    then
-        printf "\e[31mtarget cluster cannot be empty\e[0m\n"
-        exit 1
-    fi
     printf "\e[34mEnter the machine class file path\e[0m\n"
     read MACHINECLASS
     if [ ! -f "$MACHINECLASS" ]
@@ -139,14 +118,41 @@ else
         printf "\e[31m$MACHINECLASS is not a valid file path\e[0m\n"
         exit 1
     fi
+    printf "\e[34mDo you want to create the secret automatically ? (true/false)\e[0m\n"
+    printf "\e[33mNote: This is only possible if your control cluster is a gardener shoot.\e[0m\n"
+    read CREATE_SECRET
+    if [ -z "$CREATE_SECRET" ]
+    then
+        printf "\e[31mentered value cannot be empty\e[0m\n"
+        exit 1
+    fi
+    if [ "$CREATE_SECRET" != true ] && [ "$CREATE_SECRET" != false ]
+    then
+        printf "\e[31mentered value must be a boolean\e[0m\n"
+        exit 1
+    fi
+    if [ "$CREATE_SECRET" = false ]
+    then
+        printf "\e[34mEnter the absolute path for the secret to be applied.\e[0m\n"
+        read SECRET_PATH
+    fi
+
     printf "\e[34mEnter the namespace on which you want to operate in the control cluster\e[0m\n"
     read NAMESPACE; \
     printf "\e[34mEnter control kubeconfig path\e[0m\n";
     read CONTROL_KUBECONFIG_PATH;
+    if [ ! -f "$CONTROL_KUBECONFIG_PATH" ]
+    then
+        printf "\e[31"$CONTROL_KUBECONFIG_PATH" is not a valid filepath\e[0m\n"
+        exit 1
+    fi
     printf "\e[34mEnter target kubeconfig path\e[0m\n";
     read TARGET_KUBECONFIG_PATH;
-#    echo "enter cluster provider(gcp|aws|azure|vsphere|openstack|alicloud|metal|equinix-metal)"; \
-#    read PROVIDER;
+    if [ ! -f "$TARGET_KUBECONFIG_PATH" ]
+    then
+        printf "\e[31"$TARGET_KUBECONFIG_PATH" is not a valid filepath\e[0m\n"
+        exit 1
+    fi
     ./hack/non_gardener_local_setup.sh --namespace $NAMESPACE --control-kubeconfig-path "$CONTROL_KUBECONFIG_PATH" --target-kubeconfig-path "$TARGET_KUBECONFIG_PATH" --provider aws
     cd -
     cd ../../..
@@ -211,9 +217,12 @@ EOF
 
 if [ "$IS_CONTROL_CLUSTER_SEED" = false ]
 then
-  if command -v gardenctl &> /dev/null; then
+  if [ "$CREATE_SECRET" = true ]; then
     create_test_mc_secret
+  else
+    kubectl apply --kubeconfig="$CONTROL_KUBECONFIG" -f "$SECRET_PATH"
   fi
+
 fi
 
 printf "\e[33mStarting integration tests...\e[0m\n"
@@ -225,12 +234,11 @@ printf "\e[32mIntegration tests completed successfully\e[0m\n"
 
 if [ "$IS_CONTROL_CLUSTER_SEED" = false ]
 then
-  if command -v gardenctl &> /dev/null; then
     set +e
     kubectl --kubeconfig=$CONTROL_KUBECONFIG delete secret test-mc-secret
     set -e
     printf "\e[32mSuccessfully deleted test_mc_secret on control cluster\e[0m\n"
-  fi
+
 fi
 
 cd ../../..
